# Gets the list of fake users from the test API. The list splits into
# items, one per user.
module = "PurpleFlow.Nodes.Http"

[config]
method = "GET"
url = "https://jsonplaceholder.typicode.com/users"
